"""empty message

Revision ID: 0470473c22b3
Revises: 
Create Date: 2024-06-07 11:05:52.561932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0470473c22b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('name_of_the_restaurant', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
 # op.create_table('restaurant',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('name', sa.String(length=100), nullable=False),
    #     sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('menu',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('name', sa.String(length=100), nullable=False),
    #     sa.Column('description', sa.Text(), nullable=True),
    #     sa.Column('price', sa.Float(), nullable=False),
    #     sa.Column('category', sa.String(length=50), nullable=False),
    #     sa.Column('restaurant_id', sa.Integer(), nullable=False),
    #     sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    #     sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('table',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('number', sa.String(length=10), nullable=False),
    #     sa.Column('restaurant_id', sa.Integer(), nullable=False),
    #     sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    #     sa.PrimaryKeyConstraint('id')
    # )

    op.create_table('order',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('restaurant_id', sa.Integer(), nullable=False),
        sa.Column('table_id', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('payment_method', sa.String(length=50), nullable=False),
        sa.Column('total_price', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id']),
        sa.ForeignKeyConstraint(['table_id'], ['table.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('order_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('menu_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
      
        sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
  
def downgrade():
    op.drop_table('order_item')
    op.drop_table('order')
    # op.drop_table('user')
    # ### end Alembic commands ###
    # op.drop_table('menu')
    # op.drop_table('restaurant')
    # op.drop_table('table')

